### PR TITLE
fix remaining warnings (on-repo)

### LINKED ISSUE #113: Compiler warnings in `COO_Matrix` class
### Description how to reproduce the bug

Building GridKit with `-Wconversion -Wall -Wpedantic` flags triggers several compiler warnings in COO_Matrix class. Many of these are converting `-1` to an unsigned integer.

More details below:

<details>

```
In file included from /src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:12:
In file included from /src/gridkit/GridKit/src/Model/PowerElectronics/SystemModelPowerElectronics.hpp:9:
/src/gridkit/GridKit/src/CircuitGraph.hpp:108:51: warning: unused parameter 'verbose' [-Wunused-parameter]
void CircuitGraph<N, E>::printBiPartiteGraph(bool verbose)
                                                  ^
/src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:40:41: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
  induct->setExternalConnectionNodes(1, -1);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~    ^~
/src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:62:42: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
  vsource->setExternalConnectionNodes(0, -1);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~    ^~
In file included from /src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:9:
In file included from /src/gridkit/GridKit/src/Model/PowerElectronics/Capacitor/Capacitor.hpp:6:
In file included from /src/gridkit/GridKit/src/Model/PowerElectronics/CircuitComponent.hpp:8:
In file included from /src/gridkit/GridKit/src/Model/Evaluator.hpp:5:
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:80: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
                                                                       ~~~~~~~ ^~
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:560:9: note: in instantiation of member function 'COO_Matrix<double, unsigned long>::sortSparseCOO' requested here
  this->sortSparseCOO(this->row_indices_, this->column_indices_, this->values_);
        ^
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:129:11: note: in instantiation of member function 'COO_Matrix<double, unsigned long>::sortSparse' requested here
    this->sortSparse();
          ^
/src/gridkit/GridKit/src/Model/PowerElectronics/SystemModelPowerElectronics.hpp:246:114: note: in instantiation of member function 'COO_Matrix<double, unsigned long>::getEntries' requested here
        std::tuple<std::vector<IdxT>&, std::vector<IdxT>&, std::vector<ScalarT>&> tpm = component->getJacobian().getEntries();
                                                                                                                 ^
/src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:98:13: note: in instantiation of member function 'GridKit::PowerElectronicsModel<double, unsigned long>::evaluateJacobian' requested here
  sysmodel->evaluateJacobian();
            ^
In file included from /src/gridkit/GridKit/examples/PowerElectronics/RLCircuit/RLCircuit.cpp:9:
In file included from /src/gridkit/GridKit/src/Model/PowerElectronics/Capacitor/Capacitor.hpp:6:
In file included from /src/gridkit/GridKit/src/Model/PowerElectronics/CircuitComponent.hpp:8:
In file included from /src/gridkit/GridKit/src/Model/Evaluator.hpp:5:
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:94: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
                                                                                     ~~~~~~~ ^~
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:53: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
                                               ~~~~ ^~
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:65: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
                                                           ~~~~ ^~
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:28: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
                      ~~~~ ^~
/src/gridkit/GridKit/src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp:783:39: warning: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Wsign-conversion]
            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
```

</details>

### GridKit™ version

Version >= 0.1

### System and environment details

Reproduced at MacOS with GCC and Clang compilers.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by superwhiskers**
this is just #123 but the branch is on the main repository. below is copied from the original pull request

this pull request fixes the remaining warnings resulting from the addition of `-Wall -Wextra -Wconversion -Wpedantic` to the default cxxflags. these were missed in the initial pull request due to the source files they're in being gated behind the `GRIDKIT_ENABLE_IPOPT` define.

this pull request also removes some unnecessary commented out flags in the root `CMakeLists.txt` file due to them being superseded by the default flag list and also being covered by the `RelWithDebInfo` and `Debug` `CMAKE_BUILD_TYPE` values (iirc).

### CODE REVIEW

File: src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp [hunk 1]
```diff
@@ -780,7 +781,9 @@ inline void COO_Matrix<ScalarT, IdxT>::sortSparseCOO(std::vector<IdxT>& rows, st
   std::sort(std::begin(ordervec),
             std::end(ordervec),
             [&](int i1, int i2)
-            { return (rows[i1] < rows[i2]) || (rows[i1] == rows[i2] && columns[i1] < columns[i2]); });
+            { return (rows[static_cast<size_t>(i1)] < rows[static_cast<size_t>(i2)])
+                     || (rows[static_cast<size_t>(i1)] == rows[static_cast<size_t>(i2)]
+                         && columns[static_cast<size_t>(i1)] < columns[static_cast<size_t>(i2)]); });
```
Comment (alexander-novo) [inline src/LinearAlgebra/SparseMatrix/COO_Matrix.hpp]: Another one - no need to assert that `i1` and `i2` are `int` here - the compiler is actually already casting from `size_t` to `int` because of the signature of the lambda, then immediately converting right back to `size_t` again. Just use `auto` imo

**Comment by superwhiskers** [comment]
@pelesh, regarding [this comment](https://github.com/ORNL/GridKit/pull/123/files#r2123864801), it should be safe to just swap the type of `size_` in `CircuitComponent` to `size_t` instead of `IdxT`. it's 1) related to the size of an STL container (iirc) and 2) not used for much else other than describing the size of one. that would be the cleaner change given just how much it's used

**Comment by pelesh** [comment]
> @pelesh, regarding [this comment](https://github.com/ORNL/GridKit/pull/123/files#r2123864801), it should be safe to just swap the type of `size_` in `CircuitComponent` to `size_t` instead of `IdxT`. it's 1) related to the size of an STL container (iirc) and 2) not used for much else other than describing the size of one. that would be the cleaner change given just how much it's used

I think so. @alexander-novo, @reid-g please chime in.

File: examples/PowerElectronics/RLCircuit/RLCircuit.cpp [hunk 2]
```diff
@@ -59,7 +59,7 @@ int main(int /* argc */, char const** /* argv */)
   GridKit::VoltageSource<double, size_t>* vsource = new GridKit::VoltageSource<double, size_t>(idoff, vinit);
   // Form index to node uid realations
   // input
-  vsource->setExternalConnectionNodes(0, -1);
+  vsource->setExternalConnectionNodes(0, static_cast<size_t>(-1));
   // output
```
Comment (pelesh) [inline examples/PowerElectronics/RLCircuit/RLCircuit.cpp:63]: This is outside the scope of this PR, but it would be good to create a constant expression like
```c++
static constexpr IdxT ground_node_ = static_cast<IdxT>(-1);
```
and use that instead of explicitly entering -1. Here negative one is used to denote grounded node(s) in the circuit.

Comment (pelesh) [reply examples/PowerElectronics/RLCircuit/RLCircuit.cpp:63]: CC @reid-g

File: src/Model/PowerFlow/Generator4Param/Generator4Param.cpp [hunk 3]
```diff
@@ -325,16 +325,16 @@ namespace GridKit
     if (t >= ti && t < tf)
     {
       // Interpolate from look-up table
-      Edp_est = (table_[n + 1][3] - table_[n][3]) / (table_[n + 1][0] - table_[n][0]) * (t - table_[n][0]) + table_[n][3];
-      Eqp_est = (table_[n + 1][4] - table_[n][4]) / (table_[n + 1][0] - table_[n][0]) * (t - table_[n][0]) + table_[n][4];
+      Edp_est = (table_[static_cast<size_t>(n + 1)][3] - table_[static_cast<size_t>(n)][3]) / (table_[static_cast<size_t>(n + 1)][0] - table_[static_cast<size_t>(n)][0]) * (t - table_[static_cast<size_t>(n)][0]) + table_[static_cast<size_t>(n)][3];
+      Eqp_est = (table_[static_cast<size_t>(n + 1)][4] - table_[static_cast<size_t>(n)][4]) / (table_[static_cast<size_t>(n + 1)][0] - table_[static_cast<size_t>(n)][0]) * (t - table_[static_cast<size_t>(n)][0]) + table_[static_cast<size_t>(n)][4];
     }
```
Comment (pelesh) [inline src/Model/PowerFlow/Generator4Param/Generator4Param.cpp:330]: Since the `table_` is just a `std::vector<std::vector< >>` type, perhaps we should declare `n` and all looping indices to be of type `size_t`?

**Review by pelesh — APPROVED** [review]
Compiles cleanly and all tests pass. I made a few optional suggestions. Otherwise, it is ready to merge.

File: examples/PowerElectronics/RLCircuit/RLCircuit.cpp (hunk 2 above)
Comment (alexander-novo) [reply examples/PowerElectronics/RLCircuit/RLCircuit.cpp:63]: I agree that makes sense and will avoid a magic number lint in the future.
